version: "2"
services:

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    environment:
      - INFLUXDB_DB=climate
      - INFLUXDB_USER=db_user
      - INFLUXDB_PASSWORD=db_password
    ports:
      - 8086:8086
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - INFLUXDB_DB=climate
      - INFLUXDB_USER=db_user
      - INFLUXDB_PASSWORD=db_password
      - INFLUXDB_PORT=8086
    ports:
      - 3000:3000
    volumes:
      - ./conf/grafana/provisioning:/etc/grafana/provisioning
      - ./conf/grafana/dashboards:/dashboards
    restart: unless-stopped
